name: Auto Build and Zip

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Project
      run: |
        # Add your build commands here
        echo "Building project..."

    - name: Zip Project
      run: |
        zip -r shopee_downloader.zip . -x "*.git*" "*.github*"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: project-zip
        path: shopee_downloader.zip